-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------

CREATE SCHEMA printshop_providers AUTHORIZATION user_pg;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_providers.companies_pages (
    account_id uuid NOT NULL CONSTRAINT pk_companies_pages PRIMARY KEY,
    rewrite_name character varying(32) NULL CONSTRAINT uk_companies_pages_rewrite_name UNIQUE,
    page_title character varying(128) NOT NULL,
    logo_meta jsonb DEFAULT NULL,
    site_url character varying(512) NOT NULL,
    page_status int2 NOT NULL, -- 1=DRAFT, 2=HIDDEN', 3=PUBLISHED, 4=PUBLISHED_SHARED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------

CREATE SCHEMA printshop_controls AUTHORIZATION user_pg;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_controls.element_templates (
    template_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_element_templates PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    param_name character varying(32) NULL,
    template_caption character varying(64) NOT NULL,
    element_type int2 NOT NULL, -- 1=GROUP, 2=ELEMENT_LIST
    element_detailing int2 NOT NULL, -- 1=NORMAL, 2=EXTENDED
    element_body jsonb NOT NULL,
    template_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_controls.element_templates (template_id, tag_version, param_name, template_caption, element_type, element_detailing, element_body, template_status, created_at, updated_at)
VALUES (1, 1, 'Product', 'Поля листовой продукции', 2/*ELEMENT_LIST*/, 1/*NORMAL*/, '[
  {
    "id": "%parentId%Quantity",
    "caption": "Тираж",
    "type": "NUMBER",
    "required": true,
    "view": "TEXT",
    "values": [
      {
        "id": "%parentId%_value",
        "defaultValue": 1000,
        "minValue": 1,
        "maxValue": 1000000
      }
    ],
    "measure": "шт"
  },

  {
    "id": "%parentId%SimilarTypes",
    "caption": "Видов",
    "type": "NUMBER",
    "required": true,
    "view": "TEXT",
    "values": [
      {
        "id": "%parentId%_value",
        "defaultValue": 1,
        "minValue": 1,
        "maxValue": 100
      }
    ]
  },

  {
    "id": "%parentId%FormatX",
    "caption": "Длина",
    "type": "NUMBER",
    "required": true,
    "view": "TEXT",
    "values": [
      {
        "id": "%parentId%_value",
        "defaultValue": 297,
        "minValue": 1,
        "maxValue": 1020
      }
    ],
    "measure": "мм"
  },

  {
    "id": "%parentId%FormatY",
    "caption": "Ширина",
    "type": "NUMBER",
    "required": true,
    "view": "TEXT",
    "values": [
      {
        "id": "%parentId%_value",
        "defaultValue": 210,
        "minValue": 1,
        "maxValue": 1020
      }
    ],
    "measure": "мм"
  },

  {
    "id": "%parentId%PrintType",
    "type": "NUMBER",
    "caption": "Вид печати",
    "required": true,
    "view": "RADIO",
    "values": [
      {
        "id": "%parentId%_Any",
        "caption": "Любая печать"
      },
      {
        "id": "%parentId%_Offset",
        "caption": "Офсетная печать"
      },
      {
        "id": "%parentId%_Digital",
        "caption": "Цифровая печать"
      }
    ]
  }]', 2/*ENABLED*/, '2023-07-03 16:22:50.911157', NULL),
(2, 1, 'ProcessMedia', 'Бумага', 1/*GROUP*/, 1/*NORMAL*/, '[
  {
    "id": "%parentId%_Type",
    "caption": "Тип бумаги",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "dictionary": "media-type",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ]
  },
  {
    "id": "%parentId%_Density",
    "caption": "Плотность",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "dictionary": "media-density",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ],
    "measure": "г/м2"
  },
  {
    "id": "%parentId%_Texture",
    "caption": "Фактура",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "dictionary": "media-texture",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ]
  },
  {
    "id": "%parentId%_Color",
    "caption": "Цвет",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "dictionary": "media-color",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ]
  }
]', 2/*ENABLED*/, '2023-07-03 16:34:02.369491', NULL),
(3, 1, 'ProcessPackaging', 'Упаковка', 1/*GROUP*/, 1/*NORMAL*/, '[
  {
    "id": "%parentId%_Type",
    "caption": "Тип упаковки",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "values": [
      {
        "id": "%parentId%_ShrinkFilm",
        "caption": "Термоусадочная пленка"
      },
      {
        "id": "%parentId%_CorrugatedBox",
        "caption": "Гофрированная коробка"
      }
    ]
  }
]', 2/*ENABLED*/, '2023-07-03 16:38:59.254920', NULL),
(4, 1, 'ProcessPrinting', 'Печать', 1/*GROUP*/, 1/*NORMAL*/, '[
  {
    "id": "%parentId%_SideFace",
    "caption": "Лицевая сторона",
    "type": "GROUP",
    "required": true,
    "view": "BLOCK",
    "values": [
      {
        "id": "%parentId%_ColorMode",
        "caption": "Количество цветов",
        "type": "NUMBER",
        "required": true,
        "view": "COMBO",
        "values": [
          {
            "id": "%parentId%_1",
            "caption": "[ 1 ]"
          },
          {
            "id": "%parentId%_4",
            "caption": "[ 4 ]"
          }
        ]
      },

      {
        "id": "%parentId%_Varnish",
        "caption": "Лакировка",
        "type": "NUMBER",
        "required": false,
        "view": "COMBO",
        "dictionary": "varnish",
        "values": [
          {
            "id": "%parentId%_None",
            "caption": "без лакировки"
          }
        ]
      }
    ]
  },

  {
    "id": "%parentId%_SideBack",
    "caption": "Обратная сторона",
    "type": "GROUP",
    "required": false,
    "view": "BLOCK",
    "values": [
      {
        "id": "%parentId%_ColorMode",
        "caption": "Количество цветов",
        "type": "NUMBER",
        "required": true,
        "view": "COMBO",
        "values": [
          {
            "id": "%parentId%_0",
            "caption": "[ 0 ]"
          },
          {
            "id": "%parentId%_1",
            "caption": "[ 1 ]"
          },
          {
            "id": "%parentId%_4",
            "caption": "[ 4 ]"
          }
        ]
      },

      {
        "id": "%parentId%_Varnish",
        "type": "NUMBER",
        "caption": "Лакировка",
        "required": false,
        "view": "COMBO",
        "dictionary": "varnish",
        "values": [
          {
            "id": "%parentId%_None",
            "caption": "без лакировки"
          }
        ]
      }
    ]
  }
]', 2/*ENABLED*/, '2023-07-03 16:35:14.078093', NULL),
(5, 1, 'ProcessLaminating', 'Ламинация', 1/*GROUP*/, 1/*NORMAL*/, '[
  {
    "id": "%parentId%_NumberOfSides",
    "caption": "Количество сторон",
    "type": "NUMBER",
    "required": true,
    "view": "RADIO",
    "values": [
      {
        "id": "%parentId%_OneSide",
        "caption": "Одна сторона"
      },
      {
        "id": "%parentId%_TwoSides",
        "caption": "Две стороны"
      }
    ]
  },

  {
    "id": "%parentId%_LaminatingTexture",
    "caption": "Тип ламината",
    "type": "NUMBER",
    "required": true,
    "view": "COMBO",
    "dictionary": "laminating-texture",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ]
  },

  {
    "id": "%parentId%_LaminatingThikness",
    "caption": "Толщина ламината",
    "type": "NUMBER",
    "required": true,
    "view": "COMBO",
    "dictionary": "laminating-thikness",
    "values": [
      {
        "id": "%parentId%_None",
        "caption": "не указано"
      }
    ],
    "measure": "мм"
  }
]', 2/*ENABLED*/, '2023-07-03 16:36:48.626009', NULL);

ALTER SEQUENCE printshop_controls.element_templates_template_id_seq RESTART WITH 6;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_controls.submit_forms (
    form_id uuid NOT NULL CONSTRAINT pk_submit_forms PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    rewrite_name character varying(32) NULL CONSTRAINT uk_submit_forms_rewrite_name UNIQUE,
    param_name character varying(32) NULL CONSTRAINT uk_submit_forms_param_name UNIQUE,
    form_caption character varying(128) NOT NULL,
    form_detailing int2 NOT NULL, -- 1=NORMAL, 2=EXTENDED
    form_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_controls.submit_forms (form_id, tag_version, rewrite_name, param_name, form_caption, form_detailing, form_status, created_at, updated_at)
VALUES ('aa22434f-f09d-4b20-89c0-0785948cdc04', 1, 'flyers-001', 'Flyers', 'Флаеры', 1/*NORMAL*/, 2/*ENABLED*/, '2023-07-03 19:33:28.945816', NULL);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_controls.submit_form_elements (
    element_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_submit_form_elements PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    form_id uuid NOT NULL CONSTRAINT fk_submit_form_elements_form_id REFERENCES printshop_controls.submit_forms(form_id) ON DELETE CASCADE,
    param_name character varying(32) NOT NULL,
    element_caption character varying(64) NOT NULL,
    template_id int4 NOT NULL CONSTRAINT fk_submit_form_elements_template_id REFERENCES printshop_controls.element_templates (template_id),
    template_version int4 NOT NULL CHECK(template_version > 0),
    element_required bool NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    prev_field_id int4 NULL CHECK(prev_field_id IS NULL OR prev_field_id > 0),
    next_field_id int4 NULL CHECK(next_field_id IS NULL OR next_field_id > 0),
    order_index int8 NULL CHECK(order_index IS NULL OR order_index > 0),
    CONSTRAINT uk_submit_form_elements_form_id_param_name UNIQUE (form_id, param_name)
);

CREATE INDEX ix_submit_form_elements_form_id_order_index ON printshop_controls.submit_form_elements (form_id, order_index);

INSERT INTO printshop_controls.submit_form_elements (element_id, tag_version, form_id, param_name, element_caption, template_id, template_version, element_required, created_at, updated_at, prev_field_id, next_field_id, order_index)
VALUES (1, 1, 'aa22434f-f09d-4b20-89c0-0785948cdc04', 'Product', 'Поля листовой продукции', 1, 1, true, '2023-07-15 13:49:58.567032', NULL, null, null, 1048576);

ALTER SEQUENCE printshop_controls.submit_form_elements_element_id_seq RESTART WITH 2;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_controls.submit_form_versions (
    form_id uuid NOT NULL CONSTRAINT fk_submit_form_versions_form_id REFERENCES printshop_controls.submit_forms (form_id) ON DELETE CASCADE,
    version int4 NOT NULL CHECK(version > 0),
    rewrite_name character varying(32) NULL,
    form_caption character varying(128) NOT NULL,
    form_detailing int2 NOT NULL, -- 1=NORMAL, 2=EXTENDED
    compiled_body jsonb NOT NULL,
    activity_status int2 NOT NULL, -- 1=DRAFT, 2=TESTING, 3=PUBLISHED, 4=ARCHIVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    CONSTRAINT pk_submit_form_versions_form_id_version PRIMARY KEY (form_id, version),
    CONSTRAINT uk_submit_form_versions_rewrite_name_activity_status UNIQUE (rewrite_name, activity_status)
);

INSERT INTO printshop_controls.submit_form_versions (form_id, version, rewrite_name, form_caption, form_detailing, compiled_body, activity_status, created_at, updated_at)
VALUES ('aa22434f-f09d-4b20-89c0-0785948cdc04', 1, 'flyers-001', 'Флаеры', 1/*NORMAL*/, '[]', 3/*PUBLISHED*/, '2023-07-03 19:33:28.945816', NULL),
       ('aa22434f-f09d-4b20-89c0-0785948cdc04', 2, 'flyers-001', 'Флаеры', 1/*NORMAL*/, '[]', 2/*TESTING*/, '2023-07-03 19:33:28.945816', NULL);

-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------

CREATE SCHEMA printshop_dictionaries AUTHORIZATION user_pg;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.laminate_types (
    type_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_laminate_types PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    type_caption character varying(64) NOT NULL,
    type_status int4 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_dictionaries.laminate_types (type_id, tag_version, type_caption, type_status, created_at, updated_at)
VALUES
    (1, 1, 'глянцевый', 2/*ENABLED*/, '2023-07-30 12:30:52.651613', NULL);

ALTER SEQUENCE printshop_dictionaries.laminate_types_type_id_seq RESTART WITH 2;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.paper_colors (
    color_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_paper_colors PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    color_caption character varying(64) NOT NULL,
    color_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_dictionaries.paper_colors (color_id, tag_version, color_caption, color_status, created_at, updated_at)
VALUES
    (1, 1, 'белый', 2/*ENABLED*/, '2023-07-26 20:56:43.894664', NULL);

ALTER SEQUENCE printshop_dictionaries.paper_colors_color_id_seq RESTART WITH 2;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.paper_factures (
    facture_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_paper_factures PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    facture_caption character varying(64) NOT NULL,
    facture_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_dictionaries.paper_factures (facture_id, tag_version, facture_caption, facture_status, created_at, updated_at)
VALUES
    (1, 2, 'глянцевая', 2/*ENABLED*/, '2023-07-26 20:53:18.942332', NULL),
    (2, 2, 'матовая', 2/*ENABLED*/, '2023-07-26 20:53:39.478106', NULL),
    (3, 1, 'гладкая', 2/*ENABLED*/, '2023-07-29 13:30:58.387279', NULL);

ALTER SEQUENCE printshop_dictionaries.paper_factures_facture_id_seq RESTART WITH 4;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.print_formats (
    format_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_print_formats PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    format_caption character varying(64) NOT NULL,
    format_length int4 NOT NULL CHECK(format_length > 0 AND format_length < 1000000000), -- mm * 1000
    format_width int4 NOT NULL CHECK(format_width > 0 AND format_width < 1000000000), -- mm * 1000
    format_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_dictionaries.print_formats (format_id, tag_version, format_caption, format_length, format_width, format_status, created_at, updated_at)
VALUES
    (1, 1, 'A4 (210 x 297 mm)',210000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (2, 1, 'A3 (297 x 420 mm)',297000,420000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (3, 1, '90 x 50 mm',90000,50000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (4, 1, 'A5 (148 x 210 mm)',148000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (5, 1, 'A6 (105 x 148 mm)',105000,148000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (6, 1, '99 x 210 mm',99000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (7, 1, '55 x 85 mm',55000,85000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (8, 1, '110 x 210 mm',110000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (9, 1, '150 x 297 mm',150000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (10, 1, '70 x 100 mm',70000,100000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (11, 1, 'Euro (110 x 220 mm)',110000,220000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (12, 1, 'C5 (162 x 229 mm)',162000,229000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (13, 1, 'C4 (229 x 324 mm)',229000,324000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (14, 1, '90 x 90 mm',90000,90000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (15, 1, '100 x 150 mm',100000,150000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (16, 1, '100 x 200 mm',100000,200000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (17, 1, '230 x 410 mm (47х65 см/3)',410000,230000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (18, 1, '520 x 360 mm',520000,360000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (19, 1, '250 x 330 mm',250000,330000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (20, 1, '520 x 360 mm (72x104/4)',520000,360000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (23, 1, 'SRA3 (320 x 450 mm)',320000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (24, 1, 'max (330 x 485 mm)',330000,485000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (25, 1, '350 x 500 mm',350000,500000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (26, 1, '250 х 450 mm (70х100 см/6)',250000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (30, 1, '320 х 450 mm (64х90 см/4)',320000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (31, 1, '325 х 470 mm (65х47 см/2)',325000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (32, 1, '650 x 470 mm',650000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (33, 1, '640 x 450 mm',650000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (34, 1, '500 x 700 mm',500000,700000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (35, 1, '620 x 470 mm',620000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (36, 1, '520 x 720 mm (72x104/2)',520000,720000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (37, 1, '330 x 700 mm (70x100 см/3)',330000,700000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (38, 1, '700 x 1000 mm',700000,1000000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (39, 1, '640 x 900 mm',640000,900000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (40, 1, '620 x 940 mm',620000,940000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (41, 1, '720 х 1040 мм',720000,1040000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (42, 1, 'А1 (594 х 841 мм)',841000,594000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (43, 1, 'А2 (420 х 594 мм)',594000,420000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (44, 1, '330 x 350 mm (70x100 см/6)',350000,330000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (45, 1, '297 х 210 мм',297000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL),
    (46, 1, '420 х 297 мм',420000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL);

ALTER SEQUENCE printshop_dictionaries.print_formats_format_id_seq RESTART WITH 47;

-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------

CREATE SCHEMA printshop_catalog AUTHORIZATION user_pg;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_catalog.boxes (
    box_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_boxes PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    box_article character varying(32) NULL CONSTRAINT uk_boxes_box_article UNIQUE,
    box_caption character varying(64) NOT NULL,
    box_length int4 NOT NULL CHECK(box_length > 0 AND box_length < 10000001),-- mm * 1000
    box_width int4 NOT NULL CHECK(box_width > 0 AND box_width < 10000001), -- mm * 1000
    box_depth int4 NOT NULL CHECK(box_depth > 0 AND box_depth < 10000001), -- mm * 1000
    box_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

INSERT INTO printshop_catalog.boxes (box_id, tag_version, box_article, box_caption, box_length, box_width, box_depth, box_status, created_at, updated_at)
VALUES
    (1, 1, 'T-21-310x26x380', 'СДЭК', 310, 260, 380, 2/*ENABLED*/, '2023-07-28 19:47:00.917593', NULL),
    (2, 1, 'T-23-300x300x300', 'СДЭК', 300, 300, 300, 2/*ENABLED*/, '2023-07-28 19:49:04.261215', NULL),
    (3, 1, 'T-23-310x230x195', 'СДЭК', 310, 230, 195, 2/*ENABLED*/, '2023-07-30 12:28:57.095098', NULL);

ALTER SEQUENCE printshop_catalog.boxes_box_id_seq RESTART WITH 4;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_catalog.laminates (
    laminate_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_laminates PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    laminate_article character varying(32) NULL CONSTRAINT uk_laminates_laminate_article UNIQUE,
    laminate_caption character varying(64) NOT NULL,
    type_id int4 NOT NULL CHECK(type_id > 0),
    laminate_length int4 NOT NULL CHECK(laminate_length > 0 AND laminate_length < 1000000001), -- mm * 1000
    laminate_weight int4 NOT NULL CHECK(laminate_weight > 0 AND laminate_weight < 10001), -- g/m2
    laminate_thickness int4 NOT NULL CHECK(laminate_thickness > 0 AND laminate_thickness < 1000001), -- mkm
    laminate_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

CREATE INDEX ix_laminates_type_id ON printshop_catalog.laminates (type_id);

INSERT INTO printshop_catalog.laminates (laminate_id, tag_version, laminate_article, laminate_caption, type_id, laminate_length, laminate_weight, laminate_thickness, laminate_status, created_at, updated_at)
VALUES
    (1, 1, 'lam-1', 'Глянцевый 450', 1, 10000, 450, 30, 2/*ENABLED*/, '2023-07-26 21:08:40.908057', NULL);

ALTER SEQUENCE printshop_catalog.laminates_laminate_id_seq RESTART WITH 2;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_catalog.papers (
    paper_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_papers PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    paper_article character varying(32) NULL CONSTRAINT uk_papers_paper_article UNIQUE,
    paper_caption character varying(64) NOT NULL,
    color_id int4 NOT NULL CHECK(color_id > 0),
    facture_id int4 NOT NULL CHECK(facture_id > 0),
    paper_length int4 NOT NULL CHECK(paper_length > 0 AND paper_length < 10000001), -- mm * 1000
    paper_width int4 NOT NULL CHECK(paper_width > 0 AND paper_width < 10000001), -- mm * 1000
    paper_density int4 NOT NULL CHECK(paper_density > 0 AND paper_density < 10001), -- g/m2
    paper_thickness int4 NOT NULL CHECK(paper_thickness > 0 AND paper_thickness < 1000001), -- mm * 1000
    paper_sides int2 NOT NULL, -- 1=SAME, 2=DIFFERENT
    paper_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=REMOVED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL
);

CREATE INDEX ix_papers_color_id ON printshop_catalog.papers (color_id);
CREATE INDEX ix_papers_facture_id ON printshop_catalog.papers (facture_id);

INSERT INTO printshop_catalog.papers (paper_id, tag_version, paper_article, paper_caption, color_id, facture_id, paper_length, paper_width, paper_density, paper_thickness, paper_sides, paper_status, created_at, updated_at)
VALUES
    (1, 3, 'mel130-64х90', 'мелованная', 1, 2, 900, 640, 130, 100, 2/*DIFFERENT*/, 2/*ENABLED*/, '2023-07-29 13:08:45.348283', NULL),
    (2, 1, 'v130-70х100', 'мелованная', 1, 2, 1000, 700, 130, 100, 2/*DIFFERENT*/, 2/*ENABLED*/, '2023-07-29 13:13:23.991912', NULL),
    (3, 1, 'offset-80-70х100', 'офсетная', 1, 3, 1000, 700, 80, 100, 1/*SAME*/, 2/*ENABLED*/, '2023-07-29 13:38:24.199768', NULL),
    (4, 1, 'offset-170-70х100', 'мелованная', 1, 2, 1000, 700, 170, 130, 1/*SAME*/, 2/*ENABLED*/, '2023-07-30 12:41:25.813125', NULL),
    (5, 1, 'coatGlossy-170-70х100', 'мелованная', 1, 1, 1000, 700, 170, 120, 1/*SAME*/, 2/*ENABLED*/, '2023-07-30 12:43:54.456152', NULL);

ALTER SEQUENCE printshop_catalog.papers_paper_id_seq RESTART WITH 6;