-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_catalog.papers (
    paper_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_papers PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    paper_article character varying(32) NULL,
    paper_caption character varying(64) NOT NULL,
    type_id int4 NOT NULL CHECK(type_id > 0),
    color_id int4 NOT NULL CHECK(color_id > 0),
    facture_id int4 NOT NULL CHECK(facture_id > 0),
    paper_width int4 NOT NULL CHECK(paper_width > 0), -- mkm (mm * 1000)
    paper_height int4 NOT NULL CHECK(paper_height > 0), -- mkm (mm * 1000)
    paper_thickness int4 NOT NULL CHECK(paper_thickness > 0), -- mkm (mm * 1000)
    paper_density int4 NOT NULL CHECK(paper_density > 0), -- g/m2
    paper_sides int2 NOT NULL, -- 1=SAME, 2=DIFFERENT
    paper_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_papers_paper_article ON printshop_catalog.papers (paper_article) WHERE deleted_at IS NULL;
CREATE INDEX ix_papers_type_id ON printshop_catalog.papers (type_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_papers_color_id ON printshop_catalog.papers (color_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_papers_facture_id ON printshop_catalog.papers (facture_id) WHERE deleted_at IS NULL;
CREATE INDEX ix_papers_paper_density ON printshop_catalog.papers (paper_density) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_catalog.papers (paper_id, tag_version, paper_article, paper_caption, type_id, color_id, facture_id, paper_width, paper_height, paper_thickness, paper_density, paper_sides, paper_status, created_at, updated_at, deleted_at)
VALUES
    (1, 3, 'mel130-64х90', 'мелованная', 3, 1, 2, 900000, 640000, 100, 130, 2/*DIFFERENT*/, 2/*ENABLED*/, '2023-07-29 13:08:45.348283', NULL, NULL),
    (2, 1, 'v130-70х100', 'мелованная', 3, 1, 2, 1000000, 700000, 100, 130, 2/*DIFFERENT*/, 2/*ENABLED*/, '2023-07-29 13:13:23.991912', NULL, NULL),
    (3, 1, 'offset-80-70х100', 'офсетная', 5, 1, 3, 1000000, 700000, 100, 80, 1/*SAME*/, 2/*ENABLED*/, '2023-07-29 13:38:24.199768', NULL, NULL),
    (4, 1, 'offset-170-70х100', 'мелованная', 6, 1, 2, 1000000, 700000, 130, 170, 1/*SAME*/, 2/*ENABLED*/, '2023-07-30 12:41:25.813125', NULL, NULL),
    (5, 1, 'coatGlossy-170-70х100', 'мелованная', 4, 1, 1, 1000000, 700000, 120, 170, 1/*SAME*/, 2/*ENABLED*/, '2023-07-30 12:43:54.456152', NULL, NULL);

ALTER SEQUENCE printshop_catalog.papers_paper_id_seq RESTART WITH 6;