-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.print_formats (
    format_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_print_formats PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    format_caption character varying(64) NOT NULL,
    format_width int4 NOT NULL CHECK(format_width > 0), -- mkm (mm * 1000)
    format_height int4 NOT NULL CHECK(format_height > 0), -- mkm (mm * 1000)
    format_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    deleted_at timestamp with time zone NULL
);

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_dictionaries.print_formats (format_id, tag_version, format_caption, format_width, format_height, format_status, created_at, updated_at, deleted_at)
VALUES
    (1, 1, 'A4 (210 x 297 mm)',210000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (2, 1, 'A3 (297 x 420 mm)',297000,420000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (3, 1, '90 x 50 mm',90000,50000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (4, 1, 'A5 (148 x 210 mm)',148000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (5, 1, 'A6 (105 x 148 mm)',105000,148000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (6, 1, '99 x 210 mm',99000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (7, 1, '55 x 85 mm',55000,85000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (8, 1, '110 x 210 mm',110000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (9, 1, '150 x 297 mm',150000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (10, 1, '70 x 100 mm',70000,100000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (11, 1, 'Euro (110 x 220 mm)',110000,220000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (12, 1, 'C5 (162 x 229 mm)',162000,229000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (13, 1, 'C4 (229 x 324 mm)',229000,324000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (14, 1, '90 x 90 mm',90000,90000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (15, 1, '100 x 150 mm',100000,150000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (16, 1, '100 x 200 mm',100000,200000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (17, 1, '230 x 410 mm (47х65 см/3)',410000,230000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (18, 1, '520 x 360 mm',520000,360000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (19, 1, '250 x 330 mm',250000,330000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (20, 1, '520 x 360 mm (72x104/4)',520000,360000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (23, 1, 'SRA3 (320 x 450 mm)',320000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (24, 1, 'max (330 x 485 mm)',330000,485000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (25, 1, '350 x 500 mm',350000,500000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (26, 1, '250 х 450 mm (70х100 см/6)',250000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (30, 1, '320 х 450 mm (64х90 см/4)',320000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (31, 1, '325 х 470 mm (65х47 см/2)',325000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (32, 1, '650 x 470 mm',650000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (33, 1, '640 x 450 mm',650000,450000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (34, 1, '500 x 700 mm',500000,700000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (35, 1, '620 x 470 mm',620000,470000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (36, 1, '520 x 720 mm (72x104/2)',520000,720000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (37, 1, '330 x 700 mm (70x100 см/3)',330000,700000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (38, 1, '700 x 1000 mm',700000,1000000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (39, 1, '640 x 900 mm',640000,900000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (40, 1, '620 x 940 mm',620000,940000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (41, 1, '720 х 1040 мм',720000,1040000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (42, 1, 'А1 (594 х 841 мм)',841000,594000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (43, 1, 'А2 (420 х 594 мм)',594000,420000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (44, 1, '330 x 350 mm (70x100 см/6)',350000,330000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (45, 1, '297 х 210 мм',297000,210000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL),
    (46, 1, '420 х 297 мм',420000,297000,2/*ENABLED*/, '2023-01-01 00:00:00', NULL, NULL);

ALTER SEQUENCE printshop_dictionaries.print_formats_format_id_seq RESTART WITH 47;