---
app:
  name: "Print Shop Service"
  version: v0.0.0 # auto detection
  environment: local # local, dev, test, prod

debugging:
  debug: true
  authorized_user:
    id: "137b652a-2380-480f-bb95-3c78183f68f3"
    realm: "" # "printshop/users"
    kind: "standard" # "pro"
    lang: "ru-RU"
  unexpected_http_status: 599 # instead of http.StatusInternalServerError for unprocessed (unwrapped) errors
  error_caller:
    is_enabled: true
    depth: 2
    show_func: false
    upper_bounds:
      - github.com/mondegor/go-sysmess/errors/runtime
      - github.com/mondegor/go-sysmess/errors/helper
      - github.com/mondegor/go-storage/mrpostgres
      - github.com/mondegor/go-storage/mrpostgres/db

logger:
  level: debug # info, warn, error
  time_format: TimeOnly # RFC3339, RFC3339Nano, DateTime, TimeOnly, Kitchen
  json_format: false
  color_mode: true # true, false; true only if json_format=false

tracer:
  is_enabled: true

sentry:
  # dsn: http://id@127.0.0.1:9980/1
  traces_sample_rate: 1.0
  flush_timeout: 2s

servers:
  rest_server:
    read_timeout: 3s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8080
  internal_server:
    read_timeout: 3s
    write_timeout: 5s
    shutdown_timeout: 15s
    listen:
      bind_ip: 0.0.0.0
      port: 8084

storage:
  type: postgres
  host: db-postgres
  port: 5432
  username: user_pg
  password: 123456
  database: db_pg
  migrations_dir: "./migrations" # if empty automatic migration will be disabled
  migrations_table: print_shop_migrations
  max_pool_size: 10
  max_conn_lifetime: 1h
  max_conn_idle_time: 15m
  timeout: 15s

redis:
  host: db-redis
  port: 6379
  password: 123456
  read_timeout: 15s
  write_timeout: 15s

file_system:
  dir_mode: 0775
  create_dirs: true # check and create if not exists

file_providers:
  image_storage:
    name: imageStorage
    root_dir: "../img"

cors:
  allowed_origins:
    - http://print-shop.local
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Correlation-Id
    - X-Idempotency-Key
    - X-Use-Cookie
  exposed_headers:
    - X-Request-Id
  allow_credentials: true

localization:
  lang_url_param: lang
  languages: # the first language is default
    - "ru-RU"
    - "en-US"

senders:
  mail:
    # default_from: PrintShop <username@yandex.ru>
    # smtp_host: smtp.yandex.ru
    # smtp_port: 587 # STARTTLS
    # smtp_user_name: username
    # smtp_password: password
  telegram_bot:
    # name: "@Telegram_Bot"
    # token: "0000000000:AAAaaAAaaAAaaAAAA0AAaaaaAaAAAAAAa_a"

access_control:
  realms:
    - name: "admin.printshop/backend"
      auth_token:
        access_type: session
        access_expiry: 168h # tmp -> 15m
        refresh_expiry: 720h # tmp -> 2h
        length: 96
      user_kinds:
        - name: admin
          roles:
            - administrators
          session_max: 4
      register_user_kind: none
      operation_confirm:
        token_length: 96
        # code_length: 6
        session_expiry: 5m
        send_by_email:
          max_attempts: 3
          # max_resends: 8
          # min_resend_time: 1m
        send_by_phone:
          max_attempts: 3
          max_resends: 2
          # min_resend_time: 2m
    - name: "printshop/providers"
      auth_token:
        access_type: jwt
        access_expiry: 168h # tmp -> 30m
        refresh_expiry: 720h # 1 month
        length: 80
      user_kinds:
        - name: standard
          roles:
            - providers
          session_max: 4
        - name: pro
          roles:
            - providers
            - providers/pro
          session_max: 8
      register_user_kind: standard
      # operation_confirm:
        # token_length: 80
        # code_length: 6
        # session_expiry: 10m
        # send_by_email:
          # max_attempts: 5
          # max_resends: 8
          # min_resend_time: 1m
        # send_by_phone:
          # max_attempts: 5
          # max_resends: 2
          # min_resend_time: 2m
    - name: "printshop/users"
      auth_token:
        access_type: jwt
        access_expiry: 168h # tmp -> 60m
        refresh_expiry: 4320h # 180 days
        length: 64
      user_kinds:
        - name: standard
          roles:
            - users
          session_max: 4
      register_user_kind: standard
      operation_confirm:
        token_length: 64
        code_length: 4
        # session_expiry: 10m
        send_by_email:
          max_attempts: 3
          # max_resends: 8
          # min_resend_time: 1m
        send_by_phone:
          max_attempts: 3
          # max_resends: 2
          min_resend_time: 3m
  action_groups:
    - name: public-api
      base_path: "/"
      privilege: public
    - name: auth-api
      base_path: "/auth/"
      privilege: public
    - name: admin-api
      base_path: "/backend/"
      privilege: api/admin
    - name: user-api
      base_path: "/user/"
      privilege: api/users
    - name: provider-api
      base_path: "/prov/"
      privilege: api/providers
  roles_dir_path: "./roles"
  roles:
    - administrators # will be searched for administrators.yaml in dir_path and etc
    - providers
    - providers/pro
    - users
  allowed_privileges:
    - api/admin
    - api/providers
    - api/users
  allowed_permissions:
    - modAuth
    - modCatalogBox
    - modCatalogPaper
    - modCatalogLaminate
    - modControlsElementTemplate
    - modControlsSubmitForm
    - modControlsSubmitFormToPublish
    - modDictionariesMaterialType
    - modDictionariesPaperColor
    - modDictionariesPaperFacture
    - modDictionariesPrintFormat
    - modFileStation
    - modProviderAccounts
    - modWarehousing
  operation_confirm: # settings by default
    token_length: 80
    code_length: 6
    session_expiry: 10m
    send_by_email:
      max_attempts: 5
      max_resends: 8
      min_resend_time: 1m
    send_by_phone:
      max_attempts: 5
      max_resends: 2
      min_resend_time: 2m
  jwt_method: "HS256" # HS512
  jwt_secret: "The secret for symmetric security key" # OPTIONAL, ключ для расшифровки jwt токена, необходим только если используется в realms

modules_settings:
  general:
    page_size_max: 1000
    page_size_default: 50
  provider_account:
    company_page_logo:
      file_provider: imageStorage # file_providers.image_storage
  file_station:
    image_proxy:
      host: http://print-shop.local
      base_path: /img/{{path}}
      file_provider: imageStorage # file_providers.image_storage

validation:
  files:
    json:
      min_size: 1 # 1b
      max_size: 524288 # 512Kb
      max_files: 4
      check_request_content_type: true
      extensions:
        - json

  images:
    logo:
      max_width: 1920 # pixels
      max_height: 1080 # pixels
      check_body: true
      file:
        min_size: 512 # 512b
        max_size: 131072 # 128Kb
        max_files: 4
        check_request_content_type: true
        extensions:
          - jpeg
          - jpg
          - png

  mime_types:
    - type: "application/octet-stream"
      ext: psd
    - type: "application/pdf"
      ext: pdf
    - type: "application/json"
      ext: json
    - type: "application/x-tar"
      ext: tgz
    - type: "application/zip"
      ext: zip
    - type: "image/gif"
      ext: gif
    - type: "image/jpeg"
      ext: jpeg
    - type: "image/jpeg"
      ext: jpe
    - type: "image/jpeg"
      ext: jpg
    - type: "image/png"
      ext: png
    - type: "text/xml"
      ext: xml

task_schedule:
  settings:
    reload_settings:
      period: 10m
      timeout: 15s
      notification_channel: "event_settings_changed"
  auth:
    user_stat:
      request_collector:
        ready_timeout: 30s
        flush_period: 1m
        handler_timeout: 30s
        batch_size: 5 # 50
        workers_count: 1
    clean_records:
      period: 5m
      timeout: 15s
    clean_records_limit: 100
    logs_life_time: 168h # 1 week
  mailer:
    message_processor:
      ready_timeout: 30s
      read_period: 2m
      consumer_read_timeout: 2s
      consumer_write_timeout: 4s
      handler_timeout: 30s
      queue_size: 25
      workers_count: 1
      notification_channel: "event_mailer_queue_inserted"
    change_from_to_retry:
      period: 10m
      timeout: 2m
    clean_queue:
      period: 1h
      timeout: 3m
    send_retry_attempts: 3
    send_delay_correction: 15s
    change_queue_batch_size: 100
    change_retry_timeout: 30s
    change_retry_delayed: 0s
    clean_queue_batch_size: 1000
  notifier:
    notice_processor:
      ready_timeout: 30s
      read_period: 2m
      consumer_read_timeout: 2s
      consumer_write_timeout: 4s
      handler_timeout: 30s
      queue_size: 25
      workers_count: 1
      notification_channel: "event_notifier_queue_inserted"
    change_from_to_retry:
      period: 5m
      timeout: 2m
    clean_queue:
      period: 1h
      timeout: 3m
    send_retry_attempts: 3
    change_queue_batch_size: 100
    change_retry_timeout: 30s
    change_retry_delayed: 30s
    clean_queue_batch_size: 1000