---
app_name: "Print Shop Service" # env:APPX_NAME
# app_version: "v0.0.0" # env:APPX_VER
app_languages: # env:APPX_LANGS
  - "ru-RU" # the first language is default
  - "en-US"

log_level: info # debug, info, warn, error
log_time_format: DateTime # RFC3339, RFC3339Nano, DateTime, TimeOnly, Kitchen
log_json_format: true
log_color_mode: false # true, false; true only if json_format=false
log_trace_is_enabled: false
debug_is_enabled: false

stack_trace_is_enabled: true
stack_trace_depth: 2
stack_trace_show_func: false
stack_trace_upper_bounds:
  - github.com/mondegor/go-sysmess/errors/runtime
  - github.com/mondegor/go-sysmess/errors/helper
  - github.com/mondegor/go-sysmess/mrpostgres
  - github.com/mondegor/go-sysmess/mrpostgres/db

unexpected_error_http_status: 500 # 418, 599

# [IGNORE if sentry_dsn == ""]
# sentry_dsn: http://id@127.0.0.1:9980/1 # env:APPX_SENTRY_DSN [OPTIONAL]
sentry_traces_sample_rate: 1.0
sentry_flush_timeout: 2s

# db_host: db-postgres # env:APPX_DB_HOST
db_port: 5432 # env:APPX_DB_PORT
# db_username: user_pg # env:APPX_DB_USER
# db_password: 123456 # env:APPX_DB_PASSWORD
# db_database: db_pg # env:APPX_DB_NAME
db_migrations_dir: "./migrations" # if empty automatic migration will be disabled
db_migrations_table: print_shop_migrations # env:APPX_DB_MIGRATIONS_TABLE
db_max_pool_size: 2
db_max_conn_lifetime: 1h
db_max_conn_idle_time: 15m
db_timeout: 15s

# redis_host: db-redis # env:APPX_REDIS_HOST
redis_port: 6379 # env:APPX_REDIS_PORT
# redis_password: 123456 # env:APPX_REDIS_PASSWORD
redis_read_timeout: 15s
redis_write_timeout: 15s

# FileSystem (disabled)
fs_dir_mode: 0775
fs_create_dirs: true # check and create if not exists

# s3_host: s3-minio # env:APPX_S3_HOST
s3_port: 9000 # env:APPX_S3_PORT
s3_use_ssl: true
# s3_username: admin # env:APPX_S3_USER
# s3_password: 12345678 # env:APPX_S3_PASSWORD
s3_create_buckets: true # check and create if not exists

file_providers:
  # S3
  image_storage_name: imageStorage
  image_storage_bucket_name: shared-img

  # FileSystem (disabled)
  image_storage2_name: imageStorage2
  image_storage2_root_dir: "../img" # env:APPX_IMAGE_STORAGE2_ROOT_DIR

# mail_default_from: "PrintShop <user-email@example.com>" # env:APPX_MAIL_DEFAULT_FROM
# mail_smtp_host: smtp.example.com # env:APPX_MAIL_SMTP_HOST
# mail_smtp_port: 587 # env:APPX_MAIL_SMTP_PORT
# mail_smtp_user_name: username # env:APPX_MAIL_SMTP_USERNAME
# mail_smtp_password: 123abc # env:APPX_MAIL_SMTP_PASSWORD

# [IGNORE if name == ""]
# telegram_channel_name: @Telegram_Bot # env:APPX_TELEGRAM_CHANNEL_NAME
# telegram_channel_token: 0000000000:AAAaa # env:APPX_TELEGRAM_CHANNEL_TOKEN

http_server_read_timeout: 3s
http_server_write_timeout: 5s
http_server_shutdown_timeout: 15s
http_server_bind_ip: 0.0.0.0 # env:APPX_HTTP_SERVER_BIND_IP
http_server_port: 8080 # env:APPX_HTTP_SERVER_PORT

monitoring_server_read_timeout: 3s
monitoring_server_write_timeout: 5s
monitoring_server_shutdown_timeout: 15s
monitoring_server_bind_ip: 0.0.0.0 # env:APPX_MONITORING_SERVER_BIND_IP
monitoring_server_port: 8084 # env:APPX_MONITORING_SERVER_PORT

# cors_allowed_origins: # env:APPX_CORS_ALLOWED_ORIGINS
#  - http://print-shop.local
#  - http://localhost:3000
#  - http://127.0.0.1:3000
cors_allowed_methods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
cors_allowed_headers:
  - Content-Type
  - Authorization
  - X-Correlation-Id
  - X-Idempotency-Key
  - X-Use-Cookie
cors_exposed_headers:
  - X-Request-Id
cors_allow_credentials: true

access_control:
  realms:
    - name: "admin.printshop/backend"
      auth_token:
        access_type: session
        access_expiry: 15m
        refresh_expiry: 2h
        length: 96
      user_kinds:
        - name: admin
          roles:
            - administrators
          session_max: 4
      register_user_kind: none
      operation_confirm:
        token_length: 96
        # code_length: 6
        session_expiry: 5m
        send_by_email:
          max_attempts: 3
          # max_resends: 8
          # min_resend_time: 1m
        send_by_phone:
          max_attempts: 3
          max_resends: 2
          # min_resend_time: 2m

    - name: "printshop/providers"
      auth_token:
        access_type: jwt
        access_expiry: 30m
        refresh_expiry: 720h # 1 month
        length: 80
      user_kinds:
        - name: standard
          roles:
            - providers
          session_max: 4
        - name: pro
          roles:
            - providers
            - providers/pro
          session_max: 8
      register_user_kind: standard
      # operation_confirm:
        # token_length: 80
        # code_length: 6
        # session_expiry: 10m
        # send_by_email:
          # max_attempts: 5
          # max_resends: 8
          # min_resend_time: 1m
        # send_by_phone:
          # max_attempts: 5
          # max_resends: 2
          # min_resend_time: 2m

    - name: "printshop/users"
      auth_token:
        access_type: jwt
        access_expiry: 60m
        refresh_expiry: 4320h # 180 days
        length: 64
      user_kinds:
        - name: standard
          roles:
            - users
          session_max: 4
      register_user_kind: standard
      operation_confirm:
        token_length: 64
        code_length: 4
        # session_expiry: 10m
        send_by_email:
          max_attempts: 3
          # max_resends: 8
          # min_resend_time: 1m
        send_by_phone:
          max_attempts: 3
          # max_resends: 2
          min_resend_time: 3m

  action_groups:
    - name: public-api
      base_path: "/"
      privilege: public
    - name: auth-api
      base_path: "/auth/"
      privilege: public
    - name: admin-api
      base_path: "/backend/"
      privilege: api/admin
    - name: user-api
      base_path: "/user/"
      privilege: api/users
    - name: provider-api
      base_path: "/prov/"
      privilege: api/providers

  roles_dir_path: "./roles" # env:APPX_ROLES_DIR_PATH

  roles:
    - administrators # will be searched for administrators.yaml in dir_path and etc
    - providers
    - providers/pro
    - users

  allowed_privileges:
    - api/admin
    - api/providers
    - api/users

  allowed_permissions:
    - modAuth
    - modCatalogBox
    - modCatalogPaper
    - modCatalogLaminate
    - modControlsElementTemplate
    - modControlsSubmitForm
    - modControlsSubmitFormToPublish
    - modDictionariesMaterialType
    - modDictionariesPaperColor
    - modDictionariesPaperFacture
    - modDictionariesPrintFormat
    - modFileStation
    - modProviderAccounts
    - modWarehousing

#  override_auth_token:
#    access_type: jwt
#    access_expiry: 720h # 30 days
#    refresh_expiry: 1440h # 60 days
#    length: 64

  default_operation_confirm:
    token_length: 80
    code_length: 6
    session_expiry: 10m
    send_by_email:
      max_attempts: 5
      max_resends: 8
      min_resend_time: 1m
    send_by_phone:
      max_attempts: 5
      max_resends: 2
      min_resend_time: 2m
  # jwt_method: "HS256" # env:APPX_JWT_METHOD [OPTIONAL]
  # jwt_secret: "The secret for symmetric security key" # env:APPX_JWT_SECRET [OPTIONAL], ключ для расшифровки jwt токена, необходим только если используется в realms

module_settings:
  general:
    page_size_max: 1000
    page_size_default: 50

  provider_account:
    company_page_logo_provider: imageStorage # file_providers.image_storage_name

  file_station:
    # image_proxy_host: http://print-shop.local # env:APPX_IMAGE_PROXY_HOST
    image_proxy_base_path: /img/{{path}}
    image_proxy_provider: imageStorage # file_providers.image_storage_name

validation_files_json:
  min_size: 1 # 1b
  max_size: 524288 # 512Kb
  max_files: 4
  check_request_content_type: true
  extensions:
    - json

validation_images_logo:
  max_width: 1920 # pixels
  max_height: 1080 # pixels
  check_body: true
  file:
    min_size: 512 # 512b
    max_size: 131072 # 128Kb
    max_files: 4
    check_request_content_type: true
    extensions:
      - jpeg
      - jpg
      - png

allowed_mime_types:
  - type: "application/octet-stream"
    ext: psd
  - type: "application/pdf"
    ext: pdf
  - type: "application/json"
    ext: json
  - type: "application/x-tar"
    ext: tgz
  - type: "application/zip"
    ext: zip
  - type: "image/gif"
    ext: gif
  - type: "image/jpeg"
    ext: jpeg
  - type: "image/jpeg"
    ext: jpe
  - type: "image/jpeg"
    ext: jpg
  - type: "image/png"
    ext: png
  - type: "text/xml"
    ext: xml

task_schedule_settings:
  reload_settings:
    period: 7m
    timeout: 15s
    notification_channel: "event_settings_changed"
  notification_check_conn_period: 5m
  default_period_ratio: 0.1 # 10% of period

task_schedule_auth:
  user_stat_request_collector:
    ready_timeout: 5s
    flush_period: 1m
    handler_timeout: 30s
    batch_size: 100
    workers_count: 1
  clean_records:
    period: 5m
    timeout: 15s
  clean_records_limit: 100
  logs_life_time: 168h # 1 week

task_schedule_mailer:
  message_processor:
    ready_timeout: 5s
    read_period: 2m
    consumer_read_timeout: 2s
    consumer_write_timeout: 4s
    handler_timeout: 30s
    queue_size: 25
    workers_count: 1
    notification_channel: "event_mailer_queue_inserted"
  change_from_to_retry:
    period: 10m
    timeout: 2m
  clean_queue:
    period: 1h
    timeout: 3m
  send_retry_attempts: 3
  send_delay_correction: 15s
  change_queue_batch_size: 100
  change_retry_timeout: 30s
  change_retry_delayed: 0s
  clean_queue_batch_size: 1000

task_schedule_notifier:
  notice_processor:
    ready_timeout: 5s
    read_period: 2m
    consumer_read_timeout: 2s
    consumer_write_timeout: 4s
    handler_timeout: 30s
    queue_size: 25
    workers_count: 1
    notification_channel: "event_notifier_queue_inserted"
  change_from_to_retry:
    period: 10m
    timeout: 2m
  clean_queue:
    period: 1h
    timeout: 3m
  send_retry_attempts: 3
  change_queue_batch_size: 100
  change_retry_timeout: 30s
  change_retry_delayed: 30s
  clean_queue_batch_size: 1000
