-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_global.notifier_templates (
    template_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notifier_templates PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    template_group int2 NOT NULL, -- 1=USERS, 2=ADMINS
    template_name character varying(64) NULL,
    lang_code character(5) NOT NULL, -- en_EN, ru_RU
    template_caption character varying(128) NOT NULL,
    notice_props jsonb NOT NULL,
    notice_vars jsonb NOT NULL, -- cache from notice_props
    template_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_notifier_templates_template_name ON printshop_global.notifier_templates (template_name, lang_code) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_global.notifier_templates (template_id, tag_version, template_group, template_name, lang_code, template_caption, notice_props, notice_vars, template_status, created_at, updated_at, deleted_at)
VALUES
    (1, 1, 1, 'test-template', 'en_EN', 'Тестовый шаблон', '{"email": {"content": "{{ .preheader }}\nTest Content acc-{{ .accountId }}", "replyTo": "Ivan Ivanov <ivanov_test+reply@gmail.com>", "subject": "Test Subject acc-{{ .accountId }}", "fromName": "TestFrom TestovFrom", "preheader": "Test preheader", "contentType": "text/plain", "observerEmails": ["Ivan Observer <ivanov_test@gmail.com>"]}, "messenger": {"tags": ["@ivanov_test"], "chatId": "-1000000000000", "content": "Test Content {{ .accountId }}", "subject": "Test subject {{ .accountId }}"}}', '[]', 2, '2024-11-21 05:33:42.071000 +03:00', '2024-11-21 05:33:44.263000 +03:00', null);

ALTER SEQUENCE printshop_global.notifier_templates_template_id_seq RESTART WITH 2;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_global.notifier_template_vars (
    var_name character varying(32) CONSTRAINT pk_notifier_template_vars PRIMARY KEY,
    default_value character varying(128) NOT NULL,
    var_description character varying(1024) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_notifier_notice_vars_var_name ON printshop_global.notifier_template_vars (var_name);

-- INSERT INTO printshop_global.notifier_notice_vars VALUES (1,'preheader','','Заголовок, который вставляется в тело уведомления'),(5,'linkConfirmAction','','Ссылка на подтверждение действия пользователя (активация в системе, изменения емаила, пароля и т.д.)'),(20,'accountId','','Аккаунт пользователя'),(21,'accountLogin','','Логин пользователя'),(22,'accountEmail','','E-mail для уведомлений пользователя'),(23,'userName','','Имя пользователя'),(24,'userSurname','','Фамилия пользователя'),(25,'userMessage','','Текст сообщения от пользователя'),(26,'linkSetPassword','','Ссылка на установку нового пароля'),(27,'linkChangeEmail','','Ссылка на подтверждение изменения емаила');
