-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users (
    user_id uuid NOT NULL CONSTRAINT pk_users PRIMARY KEY,
    user_email character varying(64) NOT NULL,
    user_phone int8 DEFAULT NULL,
    lang_code character varying(5) NOT NULL,
    user_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=BLOCKED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_users_user_email ON printshop_auth.users (user_email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_users_user_phone ON printshop_auth.users (user_phone) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_auth.users (user_id, user_email, user_phone, lang_code, user_status, created_at, updated_at, deleted_at)
VALUES  ('5ad9475b-25e5-4014-9331-567a61c51f24', 'mondegor@gmail.com', 79262751224, 'ru-RU', 2/*ENABLED*/, '2024-12-09 04:39:08.482000 +03:00', '2024-12-09 04:39:08.482000 +03:00', NULL);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_realms (
    user_id uuid NOT NULL REFERENCES printshop_auth.users(user_id) ON DELETE CASCADE,
    user_realm character varying(32) NOT NULL, -- domain + '/' + user_group
    user_kind character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users_realms PRIMARY KEY (user_id, user_realm)
);

INSERT INTO printshop_auth.users_realms (user_id, user_realm, user_kind, created_at, updated_at)
VALUES  ('5ad9475b-25e5-4014-9331-567a61c51f24', 'printshop/providers', 'standard', '2024-12-09 04:39:08.482000 +03:00', '2024-12-09 04:39:08.482000 +03:00');

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_auth_2fa (
    user_id uuid NOT NULL CONSTRAINT pk_users_auth_2fa PRIMARY KEY REFERENCES printshop_auth.users(user_id) ON DELETE CASCADE,
    auth_2fa_type int2 NOT NULL CHECK(auth_2fa_type > 0), -- 1=PASSWORD, 2=TOTP
    auth_secret character varying(128) NOT NULL,
    cancel_secret character varying(64) NOT NULL, -- hash('generated-code')
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_activity_stat (
    user_id uuid NOT NULL CONSTRAINT pk_users_activity_stat PRIMARY KEY REFERENCES printshop_auth.users(user_id) ON DELETE CASCADE,
    last_login_ip int8 NOT NULL, -- remote addr
    last_login_ip_string character varying(32) NOT NULL, -- remote addr + proxy addr
    last_logged_at  timestamp with time zone NOT NULL,
    last_visited_at timestamp with time zone NOT NULL
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_activity_log (
    record_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users_activity_log PRIMARY KEY,
    user_id uuid NOT NULL,
    user_ip int8 NOT NULL, -- remote addr
    user_ip_string character varying(32) NOT NULL, -- remote addr + proxy addr
    user_agent  character varying(512) NOT NULL,
    request_path character varying(256) NOT NULL,
    request_status int4 NOT NULL, -- 200, 403
    visited_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_users_activity_log_visited_at ON printshop_auth.users_activity_log (visited_at);

-- --------------------------------------------------------------------------------------------------

-- CREATE TABLE printshop_auth.visitors (
--     visitor_hash uuid NOT NULL, -- hash(ip_string, agent)
--     visitor_ip_string character varying(32) NOT NULL, -- remote addr + proxy addr
--     visitor_agent  character varying(512) NOT NULL,
--     visitor_id uuid NOT NULL,
--     created_at timestamp with time zone NOT NULL DEFAULT NOW()
-- );
--
-- CREATE INDEX ix_visitors_created_at ON printshop_auth.visitors (created_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.auth_tokens (
    refresh_token character varying(128) NOT NULL CONSTRAINT pk_auth_tokens PRIMARY KEY,
    access_token character varying(128) NULL,
    access_expires_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL,
    token_scopes jsonb NOT NULL,
    token_status int2 NOT NULL, -- 1=OPENED, 2=CLOSED, 3=REVOKED, 4=UNEXPECTED_REVOKED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX iu_auth_tokens_access_token ON printshop_auth.auth_tokens (access_token);
CREATE INDEX ix_auth_tokens_user_id ON printshop_auth.auth_tokens (user_id);
CREATE INDEX ix_auth_tokens_expires_at ON printshop_auth.auth_tokens (expires_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.secure_operations (
    operation_token character varying(128) NOT NULL CONSTRAINT pk_secure_operations PRIMARY KEY,
    operation_name character varying(64) NOT NULL,
    user_id uuid NULL, -- TODO: to visitor_id ????
    confirm_actions jsonb NULL,
    remaining_attempts int2 NOT NULL CHECK(remaining_attempts >= 0), -- кол-во оставшихся попыток подтверждения текущего экшена операции
    remaining_resends int2 NOT NULL CHECK(remaining_resends >= 0), -- кол-во оставшихся попыток повторной отправки кода подтверждения
    resends_at timestamp with time zone NOT NULL, -- время, начиная с которого можно сделать повторную отправку кода подтверждения
    operation_payload bytea NULL, -- realm, visitorId, newEmail, ...
    operation_status int2 NOT NULL, -- 1=OPENED, 2=CONFIRMED, 3=UPDATING
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_secure_operations_user_id ON printshop_auth.secure_operations (user_id);
CREATE INDEX ix_secure_operations_expires_at ON printshop_auth.secure_operations (expires_at);

-- --------------------------------------------------------------------------------------------------

-- CREATE TABLE printshop_auth.secure_operations_stat (
--     visitor_id uuid NOT NULL CONSTRAINT pk_secure_operations_stat PRIMARY KEY, -- visitor_id or user_id
--     sms_code_sent_count int2 NOT NULL,
--     sms_code_last_sent_at timestamp with time zone NOT NULL,
--     unblock_after_at timestamp with time zone NULL,
--     updated_at timestamp with time zone NOT NULL DEFAULT NOW()
-- );
--
-- CREATE INDEX ix_secure_operations_stat_updated_at ON printshop_auth.secure_operations_stat (updated_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.secure_operations_log (
    record_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_secure_operations_log PRIMARY KEY,
    visitor_id uuid NOT NULL, -- visitor_id or user_id
    operation_name character varying(64) NOT NULL,
    confirm_method int2 NOT NULL, -- 1=EMAIL, 2-PHONE, 3=PASSWORD, 4=TOTP
    log_status int2 NOT NULL, -- 1=OPENED, 2=CONFIRM_SUCCESS, 3=CONFIRM_FAILED, 4=RESENT_CODE, 5=CONFIRMED
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_secure_operations_log_created_at ON printshop_auth.secure_operations_log (created_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.api_tokens (
    access_token character varying(128) NOT NULL CONSTRAINT pk_api_tokens PRIMARY KEY,
    token_name character varying(32) NOT NULL,
    user_id uuid NOT NULL,
    token_scopes jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_api_tokens_user_id ON printshop_auth.api_tokens (user_id);
CREATE INDEX ix_api_tokens_expires_at ON printshop_auth.api_tokens (expires_at);

-- --------------------------------------------------------------------------------------------------
