-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users (
    user_id uuid NOT NULL CONSTRAINT pk_users PRIMARY KEY,
    user_email character varying(64) NOT NULL,
    user_phone int8 DEFAULT NULL,
    lang_code character varying(5) NOT NULL,
    user_timezone character varying(64) NOT NULL, -- IANA-имя часового пояса пользователя
    registered_ip inet NOT NULL, -- remote addr на момент создания аккаунта (write-once)
    registered_proxy_ip inet NULL, -- proxy addr на момент создания аккаунта (для информации)
    user_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED, 4=BLOCKED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_users_user_email ON printshop_auth.users (user_email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_users_user_phone ON printshop_auth.users (user_phone) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_realms (
    user_id uuid NOT NULL REFERENCES printshop_auth.users(user_id) ON DELETE CASCADE,
    realm_id int4 NOT NULL, -- 10=printshop/users, 20=printshop/providers, 50=admin.printshop/backend
    user_kind character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users_realms PRIMARY KEY (user_id, realm_id)
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_auth_2fa (
    user_id uuid NOT NULL CONSTRAINT pk_users_auth_2fa PRIMARY KEY REFERENCES printshop_auth.users(user_id) ON DELETE CASCADE,
    auth_2fa_type int2 NOT NULL CHECK(auth_2fa_type > 0), -- 1=PASSWORD, 2=TOTP
    auth_secret character varying(128) NOT NULL, -- хеш пароля (PASSWORD) или base32 TOTP-секрет (TOTP)
    last_totp_step int8 NOT NULL DEFAULT 0, -- номер последнего использованного TOTP time-step (защита от replay, только TOTP)
    recovery_codes text[] NOT NULL DEFAULT '{}', -- массив bcrypt-хешей одноразовых аварийных кодов (PASSWORD и TOTP)
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    last_recovery_at timestamp with time zone -- время последнего расхода аварийного кода (PASSWORD и TOTP)
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_activity_stat (
    user_id uuid NOT NULL,
    realm_id int4 NOT NULL,
    last_login_ip inet NOT NULL, -- remote addr (берётся из RemoteAddr)
    last_logged_at  timestamp with time zone NOT NULL,
    last_visited_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_users_activity_stat PRIMARY KEY (user_id, realm_id),
    CONSTRAINT fk_users_activity_stat FOREIGN KEY (user_id, realm_id)
        REFERENCES printshop_auth.users_realms(user_id, realm_id) ON DELETE CASCADE
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.users_activity_log (
    record_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users_activity_log PRIMARY KEY,
    user_id uuid NOT NULL,
    realm_id int4 NOT NULL, -- 0 = realm неизвестен (реестр realm'ов разошёлся с провайдерами)
    user_ip inet NOT NULL, -- remote addr (берётся из RemoteAddr)
    user_proxy_ip inet NULL, -- proxy addr (для информации)
    user_agent  character varying(512) NOT NULL,
    request_path character varying(256) NOT NULL,
    request_status int4 NOT NULL, -- 200, 403
    visited_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_users_activity_log_visited_at ON printshop_auth.users_activity_log (visited_at);

-- --------------------------------------------------------------------------------------------------

-- CREATE TABLE printshop_auth.visitors (
--     visitor_hash uuid NOT NULL, -- hash(ip, agent)
--     visitor_ip inet NOT NULL, -- remote addr (берётся из RemoteAddr)
--     visitor_proxy_ip inet NULL, -- proxy addr (для информации)
--     visitor_agent  character varying(512) NOT NULL,
--     visitor_id uuid NOT NULL,
--     created_at timestamp with time zone NOT NULL DEFAULT NOW()
-- );
--
-- CREATE INDEX ix_visitors_created_at ON printshop_auth.visitors (created_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.sessions (
    user_id uuid NOT NULL,
    session_id int8 NOT NULL,
    user_agent character varying(512) NULL,
    last_ip inet NOT NULL, -- remote addr (берётся из RemoteAddr)
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sessions PRIMARY KEY (user_id, session_id)
);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.sessions_cleanup_queue (
    user_id uuid NOT NULL,
    session_id int8 NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sessions_cleanup_queue PRIMARY KEY (user_id, session_id)
);

CREATE INDEX ix_sessions_cleanup_queue_created_at ON printshop_auth.sessions_cleanup_queue (created_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.sessions_excess_queue (
    user_id uuid NOT NULL,
    realm_id int4 NOT NULL,
    session_max int4 NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_sessions_excess_queue PRIMARY KEY (user_id, realm_id)
);

CREATE INDEX ix_sessions_excess_queue_created_at ON printshop_auth.sessions_excess_queue (created_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.auth_tokens (
    auth_token character varying(128) NOT NULL CONSTRAINT pk_auth_tokens PRIMARY KEY,
    token_type int2 NOT NULL, -- 1=ACCESS, 2=REFRESH, 3=API
    user_id uuid NOT NULL,
    realm_id int4 NOT NULL, -- 10=printshop/users, 20=printshop/providers, 50=admin.printshop/backend
    session_id int8 NOT NULL,
    token_scopes jsonb NOT NULL,
    token_status int2 NOT NULL, -- 1=ENABLED, 2=REVOKED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_auth_tokens_user_id_session_id ON printshop_auth.auth_tokens (user_id, session_id);
CREATE INDEX ix_auth_tokens_token_type_expires_at ON printshop_auth.auth_tokens (token_type, expires_at); -- очистка refresh-токенов
CREATE INDEX ix_auth_tokens_expires_at ON printshop_auth.auth_tokens (expires_at); -- очистка не-refresh токенов

CREATE INDEX ix_auth_tokens_user_id_realm_id_session_id ON printshop_auth.auth_tokens (user_id, realm_id, session_id)
    WHERE token_type = 2 AND token_status = 1; -- 2=REFRESH, 1=ENABLED

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.secure_operations (
    operation_token character varying(128) NOT NULL CONSTRAINT pk_secure_operations PRIMARY KEY,
    operation_name character varying(64) NOT NULL,
    user_id uuid NULL, -- TODO: возможно, заменить на visitor_id
    confirm_actions jsonb NULL,
    remaining_attempts int2 NOT NULL CHECK(remaining_attempts >= 0), -- кол-во оставшихся попыток подтверждения текущего экшена операции
    remaining_resends int2 NOT NULL CHECK(remaining_resends >= 0), -- кол-во оставшихся попыток повторной отправки кода подтверждения
    resends_at timestamp with time zone NOT NULL, -- время, начиная с которого можно сделать повторную отправку кода подтверждения
    operation_payload bytea NULL, -- realm, visitorId, newEmail, ...
    operation_status int2 NOT NULL, -- 1=OPENED, 2=CONFIRMED, 3=UPDATING
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL
);

CREATE INDEX ix_secure_operations_expires_at ON printshop_auth.secure_operations (expires_at);

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_auth.secure_operations_log (
    record_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_secure_operations_log PRIMARY KEY,
    visitor_id uuid NOT NULL, -- visitor_id or user_id
    operation_name character varying(64) NOT NULL,
    confirm_method int2 NOT NULL, -- 0=UNSPECIFIED, 1=EMAIL, 2=PHONE, 3=PASSWORD, 4=TOTP
    log_status int2 NOT NULL, -- 1=OPENED, 2=RESENT_CODE, 3=CONFIRM_SUCCESS, 4=CONFIRM_FAILED, 5=CONFIRMED, 6=REVOKED, 7=APPLIED, 8=BLOCKED, 9=SESSION_OPENED
    reason int2 NOT NULL DEFAULT 0, -- 0=UNSPECIFIED, 1=WRONG_CODE, 2=ATTEMPTS_EXHAUSTED, 3=THROTTLED, 4=TOKEN_REUSE, 5=ACCESS_FORBIDDEN, 6=TOTP_REPLAY, 7=EXPIRED, 8=NOT_CONFIRMED, 9=LOGIN_NOT_EXISTS, 10=SESSION_LIMIT
    client_ip inet NOT NULL, -- remote addr (берётся из RemoteAddr)
    client_proxy_ip inet NULL, -- proxy addr (для информации)
    created_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_secure_operations_log_created_at ON printshop_auth.secure_operations_log (created_at);
CREATE INDEX ix_secure_operations_log_visitor_id_created_at ON printshop_auth.secure_operations_log (visitor_id, created_at);
CREATE INDEX ix_secure_operations_log_client_ip_created_at ON printshop_auth.secure_operations_log (client_ip, created_at);

-- --------------------------------------------------------------------------------------------------
