-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_dictionaries.paper_colors (
    color_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_paper_colors PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    color_caption character varying(64) NOT NULL,
    color_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_dictionaries.paper_colors (color_id, tag_version, color_caption, color_status, created_at, updated_at, deleted_at)
VALUES
    (1, 1, 'белый', 2/*ENABLED*/, '2023-07-26 20:56:43.894664', '2023-07-26 20:56:43.894664', NULL);

ALTER SEQUENCE printshop_dictionaries.paper_colors_color_id_seq RESTART WITH 2;