-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_global.notifier_templates (
    template_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_notifier_templates PRIMARY KEY,
    tag_version int4 NOT NULL DEFAULT 1 CHECK(tag_version > 0),
    template_group int2 NOT NULL, -- 1=USERS, 2=ADMINS
    template_name character varying(64) NULL,
    lang_code character(5) NOT NULL, -- en-US, ru-RU
    template_caption character varying(128) NOT NULL,
    notice_props jsonb NOT NULL,
    notice_vars jsonb NOT NULL, -- cache from notice_props
    template_status int2 NOT NULL, -- 1=DRAFT, 2=ENABLED, 3=DISABLED
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone NULL
);

CREATE UNIQUE INDEX uk_notifier_templates_template_name ON printshop_global.notifier_templates (template_name, lang_code) WHERE deleted_at IS NULL;

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_global.notifier_templates (template_id, tag_version, template_group, template_name, lang_code, template_caption, notice_props, notice_vars, template_status, created_at, updated_at, deleted_at)
VALUES
    (1, 1, 1, 'confirm.user.activation', 'ru-RU', 'Подтверждение регистрации пользователя', '{"mail": {"content": "Регистрация пользователя на площадке https://{{ .hostName }}/. Код подтверждения: {{ .confirmCode }}", "subject": "Подтверждение регистрации пользователя", "from_name": "PrintShop", "content_type": "text/plain"}}', '["hostName"]', 2, '2025-01-26 04:41:52.694000 +03:00', '2025-01-26 04:41:52.694000 +03:00', null),
    (2, 1, 1, 'user.registration.success', 'ru-RU', 'Регистрация успешно пройдена', '{"mail": {"content": "Вы были успешно зарегистрированы на площадке https://{{ .hostName }}/.", "subject": "Регистрация успешно пройдена", "from_name": "PrintShop", "content_type": "text/plain", "observer_emails": ["mondegor@gmail.com"]}}', '["hostName"]', 2, '2024-11-21 05:33:42.071000 +03:00', '2024-11-21 05:33:44.263000 +03:00', null),
    (3, 1, 1, 'user.was.registered', 'ru-RU', '[Admins] Уведомление о новом пользователе', '{"messenger": {"tags": ["@mondegor"], "chat_id": "-1002478328065", "content": "Новый пользователь: {{ .userEmail }} в {{ .userRealm }} "}}', '[]', 2, '2024-11-21 05:33:42.071000 +03:00', '2024-11-21 05:33:44.263000 +03:00', null),
    (4, 1, 1, 'confirm.create.session.by.mail', 'ru-RU', 'Подтверждение открытия сессии по емаилу', '{"mail": {"content": "Авторизация пользователя на площадке https://{{ .hostName }}/. Код подтверждения: {{ .confirmCode }}", "subject": "Авторизация пользователя", "from_name": "PrintShop", "content_type": "text/plain"}}', '["hostName"]', 2, '2025-01-26 04:41:52.694000 +03:00', '2025-01-26 04:41:52.694000 +03:00', null),
    (5, 1, 1, 'user.authorization.success', 'ru-RU', 'Произведена авторизация пользователя', '{"mail": {"content": "Была произведена авторизация вашего пользователя на площадке https://{{ .hostName }}/.", "subject": "Предупреждение об авторизации пользователя", "from_name": "PrintShop", "content_type": "text/plain", "observer_emails": ["mondegor@gmail.com"]}}', '["hostName"]', 2, '2024-11-21 05:33:42.071000 +03:00', '2024-11-21 05:33:44.263000 +03:00', null),
    (6, 1, 1, 'confirm.operation.by.mail', 'ru-RU', 'Подтверждение операции по емаилу', '{"mail": {"content": "Подтверждение операции ''{{ .operation }}'' на площадке https://{{ .hostName }}/. Код подтверждения: {{ .confirmCode }}", "subject": "Подтверждение операции пользователя", "from_name": "PrintShop", "content_type": "text/plain"}}', '["hostName"]', 2, '2025-01-26 04:41:52.694000 +03:00', '2025-01-26 04:41:52.694000 +03:00', null),
    (7, 1, 1, 'user.revoke.token.alert', 'ru-RU', 'Повторный отзыв refresh токена', '{"mail": {"content": "Обнаружена потенциальная угроза взлома вашего аккаунта на площадке https://{{ .hostName }}/. В целях безопасности все открытые сессии на ваших устройствах завершены.", "subject": "Предупреждение о потенциальной угрозе взлома аккаунта", "from_name": "PrintShop", "content_type": "text/plain", "observer_emails": ["mondegor@gmail.com"]}}', '["hostName"]', 2, '2024-11-21 05:33:42.071000 +03:00', '2024-11-21 05:33:44.263000 +03:00', null);

ALTER SEQUENCE printshop_global.notifier_templates_template_id_seq RESTART WITH 8;

-- --------------------------------------------------------------------------------------------------

CREATE TABLE printshop_global.notifier_template_vars (
    var_name character varying(32) CONSTRAINT pk_notifier_template_vars PRIMARY KEY,
    default_value character varying(128) NOT NULL,
    var_description character varying(1024) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uk_notifier_notice_vars_var_name ON printshop_global.notifier_template_vars (var_name);

-- --------------------------------------------------------------------------------------------------

INSERT INTO printshop_global.notifier_template_vars (var_name, default_value, var_description, created_at, updated_at)
VALUES
    ('hostName', 'printshop.local', 'Название домена проекта', '2024-11-21 13:37:18.875000 +03:00', '2024-11-21 12:37:20.237000 +03:00');
