// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package papercolorscat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{}

var en_USIndex = []uint32{ // 1 elements
	0x00000000,
} // Size: 28 bytes

const en_USData string = ""

var ru_RUIndex = []uint32{ // 1 elements
	0x00000000,
} // Size: 28 bytes

const ru_RUData string = ""

// Total table size 56 bytes (0KiB); checksum: 32CC3CAD
