version: "2"

# https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
    - asciicheck # Checks that all code identifiers does not have non-ASCII symbols in the name. [fast]
    - bodyclose # Checks whether HTTP response body is closed successfully.
    # DELAYED - cyclop # Checks function and package cyclomatic complexity. [fast]
    # DELAYED - depguard # Go linter that checks if package imports are in a list of acceptable packages. [fast]
    - copyloopvar # A linter detects places where loop variables are copied. [fast, auto-fix]
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()). [fast]
    - dupl # Detects duplicate fragments of code. [fast]
    - durationcheck # Check for two durations multiplied together.
    # - err113 # Check errors handling expressions. [auto-fix]
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - errname # Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`.
    - errorlint # Find code that can cause problems with the error wrapping scheme introduced in Go 1.13. [auto-fix]
    # DELAYED - exhaustruct # Checks if all structure fields are initialized.
    - forbidigo # Forbids identifiers.
    - forcetypeassert # Find forced type assertions.
    # DELAYED - funlen # Checks for long functions. [fast]
    - gochecknoglobals # Check that no global variables exist.
    - gochecknoinits # Checks that no init functions are present in Go code. [fast]
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocritic # Provides diagnostics that check for bugs, performance and style issues. [auto-fix]
    - gocyclo # Computes and checks the cyclomatic complexity of functions. [fast]
    - godot # Check if comments end in a period. [fast, auto-fix]
    # DELAYED - godox # Detects usage of FIXME, TODO and other keywords inside comments. [fast]
    - goheader # Check if file header matches to pattern. [fast, auto-fix]
    - gomodguard # Allow and blocklist linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations. [fast]
    - goprintffuncname # Checks that printf-like functions are named with `f` at the end. [fast]
    - gosec # Inspects source code for security problems.
    - importas # Enforces consistent import aliases. [auto-fix]
    - ineffassign # Detects when assignments to existing variables are not used. [fast]
    # - interfacebloat # A linter that checks the number of methods inside an interface. [fast]
    # - ireturn # Accept Interfaces, Return Concrete Types.
    - lll # Reports long lines. [fast]
    - makezero # Find slice declarations with non-zero initial length.
    - misspell # Finds commonly misspelled English words. [fast, auto-fix]
    - nakedret # Checks that functions with naked returns are not longer than a maximum size (can be zero). [fast, auto-fix]
    - nestif # Reports deeply nested if statements. [fast]
    - nilerr # Find the code that returns nil even if it checks that the error is not nil.
    - nilnil # Checks that there is no simultaneous return of `nil` error and an invalid value.
    - nlreturn # Checks for a new line before return and branch statements to increase code clarity. [fast, auto-fix]
    - noctx # Detects function and method with missing usage of context.Context.
    - nolintlint # Reports ill-formed or insufficient nolint directives. [fast, auto-fix]
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative. [auto-fix]
    - prealloc # Find slice declarations that could potentially be pre-allocated.
    - predeclared # Find code that shadows one of Go's predeclared identifiers. [fast]
    - promlinter # Check Prometheus metrics naming via promlint. [fast]
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. [auto-fix]
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed.
    - staticcheck # It's the set of rules from staticcheck. [auto-fix]
    - testifylint # Checks usage of github.com/stretchr/testify. [auto-fix]
    - testpackage # Linter that makes you use a separate _test package. [fast]
    - thelper # Thelper detects tests helpers which do not start with the t.Helper() method.
    - tparallel # Tparallel detects inappropriate usage of t.Parallel() method in your Go test codes.
    - unconvert # Remove unnecessary type conversions.
    - unparam # Reports unused function parameters.
    - unused # Checks Go code for unused constants, variables, functions and types.
    - wastedassign # Finds wasted assignment statements.
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc. [fast, auto-fix]
    # - wrapcheck # Checks that errors returned from external packages are wrapped.
    - wsl_v5 # Add or remove empty lines. [auto-fix]

  exclusions:
    rules:
      - path: _test\.go|tests\/
        linters:
          - dupl
          - gosec
          # - exhaustruct
          - forbidigo
          - forcetypeassert
          # - funlen
          - noctx
          - revive
          - unparam
      - path: config\/config\.go
        linters:
          - revive

  settings:
    dupl:
      threshold: 250

    lll:
      line-length: 160
      tab-width: 4

    revive:
      enable-all-rules: false
      rules:
        - name: atomic
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: comment-spacings
          severity: warning
          disabled: false
          arguments:
            - mypragma
            - otherpragma
        - name: confusing-results
          severity: warning
          disabled: false
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          severity: warning
          disabled: false
          arguments:
            - allowTypesBefore: "*testing.T,*github.com/user/repo/testing.Harness"
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          severity: warning
          disabled: false
          arguments:
            - ["call-chain", "loop"]
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          severity: warning
          disabled: false
          arguments:
            - "preserveScope"
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: false
        - name: enforce-map-style
          severity: warning
          disabled: false
          arguments:
            - "make"
        - name: enforce-slice-style
          severity: warning
          disabled: false
          arguments:
            - "make"
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: function-result-limit
          severity: warning
          disabled: false
          arguments: [3]
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: import-alias-naming
          severity: warning
          disabled: false
          arguments:
            - "^[a-z][a-z0-9]{0,}$"
        - name: import-shadowing
          severity: warning
          disabled: false
        - name: imports-blocklist
          severity: warning
          disabled: false
          arguments:
            - "crypto/md5"
            - "crypto/sha1"
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
          arguments:
            - "preserveScope"
        - name: modifies-parameter
          severity: warning
          disabled: false
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: true
        - name: range
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: redundant-import-alias
          severity: warning
          disabled: false
        - name: string-format
          severity: warning
          disabled: false
          arguments:
            - - 'core.WriteError[1].Message'
              - '/^([^A-Z]|$)/'
              - must not start with a capital letter
            - - 'fmt.Errorf[0]'
              - '/(^|[^\.!?])$/'
              - must not end in punctuation
            - - panic
              - '/^[^\n]*$/'
              - must not contain line breaks
        - name: string-of-int
          severity: warning
          disabled: false
        - name: struct-tag
          severity: warning
          disabled: false
          arguments:
            - "json,inline"
            - "bson,outline,gnu"
        - name: superfluous-else
          severity: warning
          disabled: false
          arguments:
            - "preserveScope"
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: unchecked-type-assertion
          severity: warning
          disabled: false
          arguments:
            - acceptIgnoredAssertionResult: true
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: false
          arguments:
            - allowRegex: "^_"
        - name: use-any
          severity: warning
          disabled: false
        - name: useless-break
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - ["HTTP", "JSON"]
            - []
            - - upperCaseConst: true
        - name: waitgroup-by-value
          severity: warning
          disabled: false

issues:
  include:
    #- EXC0001 # [errcheck: 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked'
    #- EXC0002 # [golint] '(comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)'
    #- EXC0003 # [golint] 'func name will be used as test\.Test.* by other packages, and that stutters; consider calling this'
    #- EXC0004 # [govet] '(possible misuse of unsafe.Pointer|should have signature)'
    #- EXC0005 # [staticcheck] 'SA4011'
    #- EXC0006 # [gosec] 'G103: Use of unsafe calls should be audited'
    #- EXC0007 # [gosec] 'G204: Subprocess launched with variable'
    #- EXC0008 # [gosec] 'G104'
    #- EXC0009 # [gosec] '(G301|G302|G307): Expect (directory permissions to be 0750|file permissions to be 0600) or less'
    #- EXC0010 # [gosec] 'G304: Potential file inclusion via variable'
    #- EXC0011 # [stylecheck] '(ST1000|ST1020|ST1021|ST1022)'
    - EXC0012 # [revive] 'exported (.+) should have comment( \(or a comment on this block\))? or be unexported'
    #- EXC0013 # [revive] 'package comment should be of the form "(.+)..."'
    - EXC0014 # [revive] 'comment on exported (.+) should be of the form "(.+)..."'
    #- EXC0015 # [revive] 'should have a package comment' (default true)

formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true

    goimports:
      local-prefixes:
        - github.com/mondegor/print-shop-back

    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mondegor/print-shop-back)

run:
  concurrency: 4
  timeout: 5m
  go: "1.25"
  exclude-dirs:
    - img
    - migrations
    - roles

output:
  sort-results: true
