---
privileges:
  - api/admin

permissions:
  - modAuth
  - modCatalogBox
  - modCatalogPaper
  - modCatalogLaminate
  - modControlsElementTemplate
  - modControlsSubmitForm
  - modControlsSubmitFormToPublish
  - modDictionariesMaterialType
  - modDictionariesPaperColor
  - modDictionariesPaperFacture
  - modDictionariesPrintFormat
  - modFileStation
  - modProviderAccounts
  - modWarehousing
