@startuml

title Взаимодействие контейнера с местом хранения

[*] --> РазместитьN

РазместитьN --> ПереместитьN
РазместитьN --> ВыдатьСписать

ПереместитьN --> ПереместитьN
ПереместитьN --> ВыдатьСписать

ВыдатьСписать --> [*]

@enduml