// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package msgcat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{
	"Confirm your identity to sign in": 0,
}

var en_USIndex = []uint32{ // 2 elements
	0x00000000, 0x0000003b,
} // Size: 32 bytes

const en_USData string = "" + // Size: 59 bytes
	"\x02To sign in, enter the confirmation code sent to your email"

var ru_RUIndex = []uint32{ // 2 elements
	0x00000000, 0x000000a2,
} // Size: 32 bytes

const ru_RUData string = "" + // Size: 162 bytes
	"\x02Чтобы войти в систему, введите код подтверждения, отправленный на ва" +
	"ш электронный адрес"

	// Total table size 285 bytes (0KiB); checksum: EAA54BC9
