// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package errcat

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func NewCatalog() catalog.Catalog {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	return cat
}

var messageKeyToIndex = map[string]int{
	"401. client is unauthorized": 5,
	"403. access forbidden":       6,
	"404. resource not found":     7,
	"Internal":                    0,
	"System":                      1,
	"Validator_gte: %[1]s, %[2]s, %[3]s, %[4]s":                                           73,
	"Validator_http_url: %[1]s, %[2]s, %[3]s":                                             71,
	"Validator_lte: %[1]s, %[2]s, %[3]s, %[4]s":                                           74,
	"Validator_max: %[1]s, %[2]s, %[3]s, %[4]s":                                           75,
	"Validator_min: %[1]s, %[2]s, %[3]s, %[4]s":                                           76,
	"Validator_required: %[1]s, %[2]s, %[3]s":                                             72,
	"Validator_tag_2d_size: %[1]s, %[2]s, %[3]s":                                          84,
	"Validator_tag_3d_size: %[1]s, %[2]s, %[3]s":                                          85,
	"Validator_tag_article: %[1]s, %[2]s, %[3]s":                                          77,
	"Validator_tag_email: %[1]s, %[2]s, %[3]s":                                            78,
	"Validator_tag_email_phone: %[1]s, %[2]s, %[3]s":                                      79,
	"Validator_tag_password: %[1]s, %[2]s, %[3]s":                                         80,
	"Validator_tag_phone: %[1]s, %[2]s, %[3]s":                                            81,
	"Validator_tag_rewrite_name: %[1]s, %[2]s, %[3]s":                                     82,
	"Validator_tag_variable: %[1]s, %[2]s, %[3]s":                                         83,
	"access forbidden":                                                                    14,
	"after node with ID=%[1]s not found":                                                  62,
	"all attempts to confirm the operation have been used":                                60,
	"box article '%[1]s' already exists":                                                  28,
	"box with ID=%[1]s not found":                                                         27,
	"confirm code is incorrect":                                                           59,
	"element template ID is required":                                                     40,
	"element template with ID=%[1]s is disabled":                                          42,
	"element template with ID=%[1]s not found":                                            41,
	"email already exists":                                                                24,
	"email is invalid":                                                                    22,
	"entity already exists":                                                               17,
	"entity is not available":                                                             16,
	"entity not found":                                                                    15,
	"entity version is invalid":                                                           18,
	"file is invalid":                                                                     20,
	"form ID is required":                                                                 33,
	"form element with ID=%[1]s not found":                                                38,
	"form with ID=%[1]s is disabled":                                                      37,
	"form with ID=%[1]s not found":                                                        34,
	"input data is incorrect: '%[1]s'":                                                    13,
	"invalid file extension: %[1]s":                                                       65,
	"invalid file size, max size = %[1]sb":                                                64,
	"invalid file size, min size = %[1]sb":                                                63,
	"invalid file total size, max total size = %[1]sb":                                    66,
	"invalid image height, max size = %[1]spx":                                            70,
	"invalid image width, max size = %[1]spx":                                             69,
	"item detailing '%[1]s' not allowed for form detailing '%[2]s'":                       39,
	"laminate article '%[1]s' already exists":                                             30,
	"laminate type ID is required":                                                        43,
	"laminate type with ID=%[1]s is not available":                                        44,
	"laminate type with ID=%[1]s not found":                                               45,
	"laminate with ID=%[1]s not found":                                                    29,
	"login is invalid":                                                                    21,
	"paper article '%[1]s' already exists":                                                32,
	"paper color ID is required":                                                          46,
	"paper color with ID=%[1]s is not available":                                          47,
	"paper color with ID=%[1]s not found":                                                 48,
	"paper facture ID is required":                                                        49,
	"paper facture with ID=%[1]s is not available":                                        50,
	"paper facture with ID=%[1]s not found":                                               51,
	"paper with ID=%[1]s not found":                                                       31,
	"param name '%[1]s' already exists":                                                   36,
	"phone already exists":                                                                25,
	"phone is invalid":                                                                    23,
	"print format ID is required":                                                         52,
	"print format with ID=%[1]s is not available":                                         53,
	"print format with ID=%[1]s not found":                                                54,
	"query %[1]s not found":                                                               26,
	"request body is not valid: '%[1]s'":                                                  8,
	"request param with key '%[1]s' contains value greater then max '%[2]s'":              11,
	"request param with key '%[1]s' has value length greater then max '%[2]s' characters": 12,
	"request param with key '%[1]s' is empty":                                             10,
	"request param with key '%[1]s' of type '%[2]s' contains incorrect value '%[3]s'":     9,
	"rewrite name '%[1]s' already exists":                                                 35,
	"sending new messages is temporarily restricted":                                      61,
	"switching from '%[1]s' to '%[2]s' is rejected":                                       19,
	"system is temporarily unavailable":                                                   3,
	"the content type '%[1]s' does not match the detected type":                           67,
	"the file with the specified key '%[1]s' was not uploaded":                            4,
	"token is already revoked":                                                            58,
	"token is expired":                                                                    55,
	"token is invalid":                                                                    56,
	"token section %[1]s is invalid":                                                      57,
	"unexpected internal error":                                                           2,
	"unsupported file type '%[1]s'":                                                       68,
}

var en_USIndex = []uint32{ // 87 elements
	// Entry 0 - 1F
	0x00000000, 0x00000016, 0x0000002a, 0x00000061,
	0x000000b2, 0x000000eb, 0x00000107, 0x00000137,
	0x0000014a, 0x00000205, 0x00000255, 0x0000027d,
	0x000002c4, 0x00000318, 0x00000339, 0x0000034a,
	0x0000035b, 0x00000373, 0x00000389, 0x000003a3,
	0x000003d1, 0x000003e1, 0x000003f2, 0x00000403,
	0x00000414, 0x00000429, 0x0000043e, 0x00000454,
	0x00000470, 0x00000493, 0x000004b4, 0x000004dc,
	// Entry 20 - 3F
	0x000004fa, 0x0000051f, 0x00000533, 0x00000550,
	0x00000574, 0x00000596, 0x000005b5, 0x000005da,
	0x00000618, 0x00000638, 0x00000661, 0x0000068c,
	0x000006a9, 0x000006d6, 0x000006fc, 0x00000717,
	0x00000742, 0x00000766, 0x00000783, 0x000007b0,
	0x000007d6, 0x000007f2, 0x0000081e, 0x00000843,
	0x00000854, 0x00000865, 0x00000884, 0x0000089d,
	0x000008b7, 0x000008ec, 0x0000091b, 0x0000093e,
	// Entry 40 - 5F
	0x00000963, 0x00000988, 0x000009a6, 0x000009d7,
	0x00000a11, 0x00000a2f, 0x00000a57, 0x00000a80,
	0x00000abd, 0x00000ad3, 0x00000b23, 0x00000b70,
	0x00000ba6, 0x00000bf1, 0x00000c1c, 0x00000c5b,
	0x00000caa, 0x00000d23, 0x00000d4c, 0x00000d7c,
	0x00000da8, 0x00000dd3, 0x00000dfe,
} // Size: 372 bytes

const en_USData string = "" + // Size: 3582 bytes
	"\x02Internal server error\x02System server error\x02Internal server erro" +
	"r [problem]\x0a\x0a418. unexpected error\x02The system is temporarily un" +
	"able to process your request. Please try again later\x02the file with th" +
	"e specified key '%[1]s' was not uploaded\x02User authorization required" +
	"\x02Forbidden - You don't have permission to access\x02Resource not foun" +
	"d\x02Request body is not valid: '%[1]s'\x0a\x0aпроверьте параметры запро" +
	"са, правильность формата json и соответствующих ему типов\x02request pa" +
	"ram with key '%[1]s' of type '%[2]s' contains incorrect value '%[3]s'" +
	"\x02request param with key '%[1]s' is empty\x02request param with key '%" +
	"[1]s' contains value greater then max '%[2]s'\x02request param with key " +
	"'%[1]s' has value length greater then max '%[2]s' characters\x02Input da" +
	"ta is incorrect: '%[1]s'\x02access forbidden\x02entity not found\x02enti" +
	"ty is not available\x02entity already exists\x02entity version is invali" +
	"d\x02switching from '%[1]s' to '%[2]s' is rejected\x02file is invalid" +
	"\x02login is invalid\x02email is invalid\x02phone is invalid\x02email al" +
	"ready exists\x02phone already exists\x02query %[1]s not found\x02box wit" +
	"h ID=%[1]s not found\x02box article '%[1]s' already exists\x02laminate w" +
	"ith ID=%[1]s not found\x02laminate article '%[1]s' already exists\x02pap" +
	"er with ID=%[1]s not found\x02paper article '%[1]s' already exists\x02fo" +
	"rm ID is required\x02form with ID=%[1]s not found\x02rewrite name '%[1]s" +
	"' already exists\x02param name '%[1]s' already exists\x02form with ID=%[" +
	"1]s is disabled\x02form element with ID=%[1]s not found\x02item detailin" +
	"g '%[1]s' not allowed for form detailing '%[2]s'\x02element template ID " +
	"is required\x02element template with ID=%[1]s not found\x02element templ" +
	"ate with ID=%[1]s is disabled\x02laminate type ID is required\x02laminat" +
	"e type with ID=%[1]s is not available\x02laminate type with ID=%[1]s not" +
	" found\x02paper color ID is required\x02paper color with ID=%[1]s is not" +
	" available\x02paper color with ID=%[1]s not found\x02paper facture ID is" +
	" required\x02paper facture with ID=%[1]s is not available\x02paper factu" +
	"re with ID=%[1]s not found\x02print format ID is required\x02print forma" +
	"t with ID=%[1]s is not available\x02print format with ID=%[1]s not found" +
	"\x02token is expired\x02token is invalid\x02token section %[1]s is inval" +
	"id\x02token is already revoked\x02confirm code is incorrect\x02all attem" +
	"pts to confirm the operation have been used\x02sending new messages is t" +
	"emporarily restricted\x02after node with ID=%[1]s not found\x02invalid f" +
	"ile size, min size = %[1]sb\x02invalid file size, max size = %[1]sb\x02i" +
	"nvalid file extension: %[1]s\x02invalid file total size, max total size " +
	"= %[1]sb\x02the content type '%[1]s' does not match the detected type" +
	"\x02unsupported file type '%[1]s'\x02invalid image width, max size = %[1" +
	"]spx\x02invalid image height, max size = %[1]spx\x02The field value must" +
	" be URL address (current value: '%[3]s')\x02The field is required\x02The" +
	" field value must be greater than or equal to %[4]s (current value: '%[3" +
	"]s')\x02The field value must be less than or equal to %[4]s (current val" +
	"ue: '%[3]s')\x02The field value must be no more than %[4]s characters" +
	"\x02The field value must be at least %[4]s characters (current value: '%" +
	"[3]s')\x02Validator_tag_article: %[1]s, %[2]s, %[3]s\x02The field value " +
	"must be email address (current value: '%[3]s')\x02The field value must b" +
	"e email address or phone number (current value: '%[3]s')\x02The field va" +
	"lue must contain only latin letters, numbers, and special characters wit" +
	"hout spaces (current value: '%[3]s')\x02Validator_tag_phone: %[1]s, %[2]" +
	"s, %[3]s\x02Validator_tag_rewrite_name: %[1]s, %[2]s, %[3]s\x02Validator" +
	"_tag_variable: %[1]s, %[2]s, %[3]s\x02Validator_tag_2d_size: %[1]s, %[2]" +
	"s, %[3]s\x02Validator_tag_3d_size: %[1]s, %[2]s, %[3]s"

var ru_RUIndex = []uint32{ // 87 elements
	// Entry 0 - 1F
	0x00000000, 0x00000031, 0x00000060, 0x0000009b,
	0x00000136, 0x00000136, 0x00000179, 0x000001a9,
	0x000001ea, 0x000002bd, 0x000002bd, 0x000002bd,
	0x000002bd, 0x000002bd, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	// Entry 20 - 3F
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	// Entry 40 - 5F
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x000002f9, 0x000002f9, 0x000002f9, 0x000002f9,
	0x0000036d, 0x000003a9, 0x00000427, 0x000004a5,
	0x000004fc, 0x0000057c, 0x0000057c, 0x000005e2,
	0x0000066f, 0x0000073c, 0x0000073c, 0x0000073c,
	0x0000073c, 0x0000073c, 0x0000073c,
} // Size: 372 bytes

const ru_RUData string = "" + // Size: 1852 bytes
	"\x02Внутренняя ошибка сервера\x02Системная ошибка сервера\x02Внутренняя " +
	"ошибка сервера [problem]\x02Система временно не может обработать ваш за" +
	"прос. Пожалуйста, повторите запрос позже\x02Требуется авторизация польз" +
	"ователя\x02Доступ к ресурсу отклонён\x02Запрашиваемый ресурс не был най" +
	"ден\x0211111Тело запроса невалидное: '%[1]s'\x0a\x0aпроверьте параметры" +
	" запроса, правильность формата json и соответствующих ему типов\x02Входн" +
	"ые данные некорректны: '%[1]s'\x02Значение поля должно являться URL адр" +
	"есом (текущее значение: %[3]s)\x02Поле обязательно для заполнения\x02Зн" +
	"ачение поля должно быть больше или равно %[4]s (текущее значение: %[3]s" +
	")\x02Значение поля должно быть меньше или равно %[4]s (текущее значение:" +
	" %[3]s)\x02Значение поля должно быть не более %[4]s символов\x02Значение" +
	" поля должно быть не менее %[4]s символов (текущее значение: %[3]s)\x02З" +
	"начение поля должно являться email адресом (current value: '%[3]s')\x02" +
	"Значение поля должно являться email адресом или номером телефона (curre" +
	"nt value: '%[3]s')\x02Значение поля должно содержать только латинские бу" +
	"квы, цифры и специальные символы кроме пробела (current value: '%[3]s')"

	// Total table size 6178 bytes (6KiB); checksum: 389D5755
